# Generated by Django 2.1 on 2018-08-06 19:30
# pylint: disable=line-too-long,invalid-name,missing-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
            ],
        ),
    ]
