# Generated by Django 2.1 on 2018-08-06 19:47
# pylint: disable=line-too-long,invalid-name,missing-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
