# Generated by Django 2.1 on 2018-08-06 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180806_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
